services:
  frontend:
    build: .
    container_name: hsenova-frontend

    ports:
      - "3000:3000"

    environment:
      NEXT_PUBLIC_API_URL: http://localhost:5000/api
      WATCHPACK_POLLING: "true"

    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next

    command: npm run dev